"""device_family

Revision ID: 8ec42a19ead5
Revises: fa9c6761af35
Create Date: 2026-09-23 11:00:20.831393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec42a19ead5'
down_revision: Union[str, Sequence[str], None] = 'fa9c6761af35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default=sa.text("'simulation'"), nullable=False))
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###
